name: Build & Deploy Static Web on AWS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      cloudfront_distribution_id: ${{ steps.tf_outputs.outputs.cloudfront_distribution_id }}
      bucket_name: ${{ steps.tf_outputs.outputs.bucket_name }}

    defaults:
      run:
        working-directory: ./infra/aws

    env:
      # AWS Login
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      TF_VAR_bucket_name: ${{ vars.BUCKET_NAME }}

      TF_CLI_ARGS_init: >-
        -backend-config="bucket=${{ vars.STATE_STORAGE_NAME }}"
        -backend-config="key=${{ github.repository }}/aws-terraform.tfstate"
        -backend-config="region=${{ vars.BACKEND_REGION != '' && vars.BACKEND_REGION || 'ap-southeast-1' }}"

    steps:
      - name: Check state storage
        if: ${{ vars.STATE_STORAGE_NAME == '' }}
        run: exit 1

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Check Format
        run: terraform fmt -check -recursive
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Export Terraform Outputs
        id: tf_outputs
        run: |
          echo "cloudfront_distribution_id=$(terraform output cloudfront_distribution_id)" >> $GITHUB_OUTPUT
          echo "bucket_name=$(terraform output s3_bucket_name)" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./portfolio-website

    steps:
      - name: Clone portfolio repo
        uses: actions/checkout@v4
        with:
          repository: phanlamthanhdu/portfolio-website
          path: portfolio-website

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_GITHUB_USERNAME=phanlamthanhdu" > .env.local

      - name: Build app
        run: |
          npm install
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy static files to S3
        run: |
          aws s3 sync dist/ s3://${{ needs.build.outputs.bucket_name }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ needs.build.outputs.cloudfront_distribution_id }} \
            --paths "/*"